Add unwrap method to access ValidatorBuilder
making/yavi pull request #263
Opened 2022-06-07 05:26 UTC by be-hase

## Motivation

Kotlin DSL(ValidatorBuilderKt) is very cool and convient.
However, there are some method that ValidatorBuilder has but does not exist in ValidatorBuilderKt.
(For example, `constraintOnTarget`)

Therefore, I want to be able to access the ValidatorBuilder held by the ValidatorBuilderKt.
Since there may be other methods that forget to support DSL in the future, I want to access ValidatorBuilder.

2022-06-07 05:51 UTC, making commented
Thanks for your contribution!
Looks good to me

2022-06-07 05:55 UTC, making requested changes

2022-06-07 05:55 UTC, making commented on src/main/kotlin/am/ik/yavi/builder/ValidatorBuilderKtDsl.kt
can you please add

```
@since 0.12.0
```

2022-06-07 05:55 UTC, making commented on src/test/kotlin/am/ik/yavi/builder/ValidatorBuilderKtDslTest.kt
> +import java.util.function.Predicate
Unused class?

2022-06-07 11:14 UTC, be-hase commented on src/main/kotlin/am/ik/yavi/builder/ValidatorBuilderKtDsl.kt
OK, fixed

2022-06-07 11:14 UTC, be-hase commented on src/test/kotlin/am/ik/yavi/builder/ValidatorBuilderKtDslTest.kt
> +import java.util.function.Predicate
Ah, soory. it's mistake 😢

2022-06-07 11:40 UTC, merged

2022-06-08 03:06 UTC, be-hase commented
thanks :)