Add isLocalDate to CharSequenceConstraint
making/yavi pull request #283
Opened 2022-11-03 13:49 UTC by ffroliva

Hi this pull request addes isLocalDate validation in CharSequenceConstraint. This validates if a given string is in ISO format or in a given pattern format.

2022-11-09 07:38 UTC, ffroliva commented
Any updates on this?

2022-11-17 07:52 UTC, making requested changes

2022-11-17 07:52 UTC, making commented on src/main/java/am/ik/yavi/constraint/CharSequenceConstraint.java
> +		return this.isValidLocalDate("yyyy-MM-dd");
`uuuu-MM-dd`

2022-11-17 07:52 UTC, making commented on src/main/java/am/ik/yavi/constraint/CharSequenceConstraint.java
> +				LocalDate.parse(x, DateTimeFormatter.ofPattern(pattern));
`DateTimeFormatter.ofPattern(pattern, locale).withResolverStyle(ResolverStyle.STRICT)`

2022-11-17 07:52 UTC, making commented on src/main/java/am/ik/yavi/constraint/CharSequenceConstraint.java
> +	 * @since 0.11.3
0.12.0

2022-11-17 07:52 UTC, making commented on src/main/java/am/ik/yavi/constraint/CharSequenceConstraint.java
> +	 * @since 0.11.3
0.12.0

2022-11-17 07:52 UTC, making commented on src/main/java/am/ik/yavi/constraint/CharSequenceConstraint.java
> +	public CharSequenceConstraint<T, E> isLocalDate() {
`isIsoLocalDate`

2022-11-17 07:52 UTC, making commented on src/main/java/am/ik/yavi/constraint/CharSequenceConstraint.java
> +	public CharSequenceConstraint<T, E> isLocalDate(String pattern) {
`isLocalDate(String pattern, Locale locale)`

2022-11-17 07:52 UTC, making commented on src/main/java/am/ik/yavi/constraint/CharSequenceConstraint.java
> +	private CharSequenceConstraint<T, E> isValidLocalDate(String pattern) {
`isValidLocalDate(String pattern, Locale locale)`

2022-11-21 00:45 UTC, making commented
@ffroliva 
Can I make changes directly and merge them?

2022-11-21 17:47 UTC, merged

2022-11-21 17:51 UTC, ffroliva commented
It was my pleasure!